# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-06 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, help_text=b'Debe ingresar la url relativa. Por ejemplo: "/contacto/"', max_length=200, unique=True, verbose_name=b'URL')),
                ('meta_title', models.CharField(blank=True, help_text=b'M\xc3\xa1ximo: 50 caracteres', max_length=50, verbose_name=b'T\xc3\xadtulo')),
                ('meta_description', models.CharField(blank=True, help_text=b'M\xc3\xa1ximo 160 caracteres', max_length=160, verbose_name=b'Descripci\xc3\xb3n')),
                ('og_title', models.CharField(blank=True, help_text=b'M\xc3\xa1ximo: 40 caracteres', max_length=40, verbose_name=b'T\xc3\xadtulo')),
                ('og_description', models.CharField(blank=True, help_text=b'M\xc3\xa1ximo 300 caracteres', max_length=300, verbose_name=b'Descripci\xc3\xb3n')),
                ('url_canonica', models.URLField(blank=True, help_text=b'Las urls relativas no est\xc3\xa1n permitidas', verbose_name=b'URL Can\xc3\xb3nica')),
                ('meta_robots', models.CharField(blank=True, help_text=b'Por ejemplo: "noindex, nofollow"', max_length=60, verbose_name=b'Etiqueta "meta:robots"')),
            ],
            options={
                'ordering': ('url',),
                'verbose_name': 'Metadata',
                'verbose_name_plural': 'Metadata',
            },
        ),
    ]
