# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-25 00:18
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pestana', models.CharField(choices=[('SO', 'SOMOS'), ('CLI', 'CLIENTES'), ('TES', 'TESTIMONIOS'), ('CO', 'CONTACTO'), ('SE', 'SERVICIOS')], default='SO', max_length=30, verbose_name='Pestaña')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('fondo', filebrowser.fields.FileBrowseField(blank=True, help_text='Tamaño Recomendado: 1080x132', max_length=200, verbose_name='Fondo:')),
            ],
            options={
                'verbose_name': 'Banners',
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.SmallIntegerField(default=0, verbose_name='Posición')),
                ('nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre')),
                ('imagen', filebrowser.fields.FileBrowseField(blank=True, help_text='Tamaño Recomendado: 172x125', max_length=200, verbose_name='Imagen')),
                ('texto_hover', models.CharField(blank=True, default='MIRA LO QUE HICIMOS', max_length=100, verbose_name='Texto hover')),
                ('ubicacion', models.CharField(blank=True, max_length=300, verbose_name='Ubicación')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=200, verbose_name='Subtítulo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombres')),
                ('apellido', models.CharField(blank=True, max_length=200, verbose_name='Apellidos')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('mensaje', ckeditor.fields.RichTextField(verbose_name='Mensaje')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('servicio', models.CharField(blank=True, max_length=200, verbose_name='Tipo de servicio')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.SmallIntegerField(default=0, verbose_name='Posición')),
                ('direccion', models.CharField(max_length=300, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'ubicacion',
                'verbose_name_plural': 'ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.SmallIntegerField(default=0, verbose_name='Posición')),
                ('email', models.CharField(max_length=120, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_servicios', models.CharField(blank=True, max_length=100, verbose_name='Título servicios')),
                ('titulo_somos', models.CharField(blank=True, max_length=100, verbose_name='Título somos')),
                ('texto_somos', ckeditor.fields.RichTextField(blank=True, verbose_name='Texto somos')),
                ('img_somos', filebrowser.fields.FileBrowseField(blank=True, help_text='Tamaño Recomendado: 309x400', max_length=200, verbose_name='Imagen')),
                ('titulo_clientes', models.CharField(blank=True, max_length=300, verbose_name='Título clientes')),
                ('boton_clientes', models.CharField(blank=True, max_length=300, verbose_name='Texto boton clientes')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Home',
            },
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.SmallIntegerField(default=0, verbose_name='Posición')),
                ('texto', models.CharField(blank=True, max_length=100, verbose_name='Texto')),
                ('texto_boton', models.CharField(blank=True, max_length=100, null=True, verbose_name='Texto de botón')),
                ('enlace_boton', models.CharField(blank=True, max_length=100, verbose_name='Enlace del botón')),
                ('imagen', filebrowser.fields.FileBrowseField(help_text='Tamaño Recomendado: 1920x570', max_length=200, verbose_name='Imagen:')),
            ],
            options={
                'verbose_name': 'Banner de Home',
                'ordering': ['position'],
                'verbose_name_plural': 'Banners de Home',
            },
        ),
        migrations.CreateModel(
            name='InfoSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default=0, editable=False, null=True, verbose_name='Creado por')),
                ('modified_by', models.IntegerField(default=0, editable=False, null=True, verbose_name='Modificado por')),
                ('email_form', models.CharField(blank=True, help_text='Separar correos con comas', max_length=200, verbose_name='Email de Formulario de Contacto')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('site', models.CharField(blank=True, help_text='Ingrese la url actual del sitio sin el slash final', max_length=60, verbose_name='URL del sitio')),
                ('ga', models.CharField(blank=True, help_text='Opcional: Inserte el código que google analitycs le\n       proporciona con el formato: UA-XXXXX-X', max_length=24, verbose_name='Google Analytics')),
            ],
            options={
                'verbose_name_plural': 'Información del Sitio',
            },
        ),
        migrations.CreateModel(
            name='SeccionCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', ckeditor.fields.RichTextField(blank=True, verbose_name='Texto')),
                ('boton', models.CharField(blank=True, max_length=100, verbose_name='Texto botón')),
                ('enlace', models.CharField(blank=True, max_length=300, verbose_name='Enlace boton')),
            ],
            options={
                'verbose_name': 'Sección clientes',
                'verbose_name_plural': 'Sección clientes',
            },
        ),
        migrations.CreateModel(
            name='SeccionContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('texto', ckeditor.fields.RichTextField(blank=True, verbose_name='Texto')),
                ('imagen', filebrowser.fields.FileBrowseField(blank=True, help_text='Tamaño recomendado:325x464', max_length=200, verbose_name='imagen')),
            ],
            options={
                'verbose_name': 'Sección Contacto',
                'verbose_name_plural': 'Sección Contacto',
            },
        ),
        migrations.CreateModel(
            name='SeccionServicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', ckeditor.fields.RichTextField(blank=True, verbose_name='Texto')),
                ('boton', models.CharField(blank=True, max_length=100, verbose_name='Texto botón')),
                ('enlace', models.CharField(blank=True, max_length=300, verbose_name='Enlace boton')),
            ],
            options={
                'verbose_name': 'Sección clientes',
                'verbose_name_plural': 'Sección clientes',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default=0, editable=False, null=True, verbose_name='Creado por')),
                ('modified_by', models.IntegerField(default=0, editable=False, null=True, verbose_name='Modificado por')),
                ('position', models.SmallIntegerField(default=0, verbose_name='Posición')),
                ('nombre', models.CharField(blank=True, max_length=120, verbose_name='Nombre')),
                ('texto', ckeditor.fields.RichTextField(blank=True, verbose_name='Texto')),
                ('imagen', filebrowser.fields.FileBrowseField(blank=True, help_text='Tamaño Recomendado: 767x460', max_length=200, verbose_name='Imagen')),
                ('icono', filebrowser.fields.FileBrowseField(blank=True, help_text='Tamaño Recomendado: 51x51', max_length=200, verbose_name='Imagen ícono')),
                ('icono2', filebrowser.fields.FileBrowseField(blank=True, help_text='Tamaño Recomendado: 70x70', max_length=200, verbose_name='Imagen ícono hover')),
                ('servicio', models.ManyToManyField(blank=True, related_name='_servicio_servicio_+', to='web.Servicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'ordering': ['position'],
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Somos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduccion', ckeditor.fields.RichTextField(blank=True, verbose_name='Introduccion')),
                ('texto', ckeditor.fields.RichTextField(blank=True, verbose_name='Texto')),
                ('imagen', filebrowser.fields.FileBrowseField(blank=True, help_text='Tamaño recomendado:470x430', max_length=200, verbose_name='imagen')),
                ('boton', models.CharField(blank=True, max_length=100, verbose_name='Texto botón')),
                ('enlace', models.CharField(blank=True, max_length=200, verbose_name='Enlace botón')),
            ],
            options={
                'verbose_name': 'Somos',
                'verbose_name_plural': 'Somos',
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.SmallIntegerField(default=0, verbose_name='Posición')),
                ('telefono', models.CharField(blank=True, max_length=120, verbose_name='Teléfono')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_tel', to='web.InfoSite')),
            ],
            options={
                'verbose_name': 'Teléfono',
                'verbose_name_plural': 'Teléfonos',
            },
        ),
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.SmallIntegerField(default=0, verbose_name='Posición')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('texto', ckeditor.fields.RichTextField(blank=True, verbose_name='Texto')),
                ('autor', models.CharField(blank=True, max_length=100, verbose_name='Autor')),
                ('imagen', filebrowser.fields.FileBrowseField(help_text='Tamaño Recomendado: 128x128', max_length=200, verbose_name='Imagen:')),
                ('active', models.BooleanField(default=True, verbose_name='Mostrar')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'ordering': ['position'],
                'verbose_name_plural': 'Testimonios',
            },
        ),
        migrations.AddField(
            model_name='email',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_email', to='web.InfoSite'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_direccion', to='web.InfoSite'),
        ),
    ]
