# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-25 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20170525_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='somos',
            name='texto_redes',
            field=models.CharField(blank=True, max_length=200, verbose_name='Texto redes sociales'),
        ),
    ]
