# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-25 23:52
from __future__ import unicode_literals

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_remove_contacto_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccioncontacto',
            name='imagen',
            field=filebrowser.fields.FileBrowseField(blank=True, help_text='Tamaño recomendado:160x45', max_length=200, verbose_name='imagen'),
        ),
    ]
