"""
Django settings for base_django110 project.

Generated by 'django-admin startproject' using Django 1.10.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
from .util import get_env
from os.path import dirname, join, realpath

PROJECT_NAME = u'Base django 1.11'
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ENV = get_env(BASE_DIR)

SECRET_KEY = ENV.get('SECRET_KEY', ENV.get('SECRET_KEY'))
AUTH_SECRET_KEY = 'my-auth-secret-key'
DEBUG = True

ALLOWED_HOSTS = ENV.get('ALLOWED_HOSTS', [])
SITE_URL = ENV.get('URL_SITE', '')
URL_SITE_SAE = ENV.get('URL_SITE_SAE', '')

# EMAIL
EMAIL_HOST = ENV.get('EMAIL_HOST', '')
EMAIL_HOST_USER = ENV.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = str(ENV.get('EMAIL_HOST_PASSWORD', ''))
DEFAULT_FROM_EMAIL = ENV.get('DEFAULT_FROM_EMAIL', '')
SERVER_EMAIL = ENV.get('SERVER_EMAIL', '')
EMAIL_PORT = ENV.get('EMAIL_PORT', '')
EMAIL_USE_TLS = True



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'zrupqqbwfhdxi)j7-+tvp_6rjixz^5lh^-$(shp8j)at9tuyqn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []

THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    # 'easy_thumbnails.processors.scale_and_crop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters',
)

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend'
    # 'apps.postulantes.backend.AuthBackend'
]

# Para normalizar nombres de archivo en formato ASCII en vez de Unicode
DEFAULT_FILE_STORAGE = 'apps.core.util.storage.ASCIIFileSystemStorage'


# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

LOCAL_APPS = [
    # Aqui van las aplicaciones de  tu local ejem: apps.web
    # 'apps.ubigeo',
    'apps.web',
]

THIRD_PART_APPS = [
    # Solo aplicaciones externas
    # 'debug_toolbar',
    'django_extensions',
    'filebrowser',
    'ckeditor',
    'ckeditor_uploader',
    'geoposition'
    # 'taggit',
    # 'captcha'
]

INSTALLED_APPS = DJANGO_APPS + LOCAL_APPS + THIRD_PART_APPS


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'admin_reorder.middleware.ModelAdminReorder',
]

ROOT_URLCONF = 'urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': ENV.get('DB_NAME'),
        'USER': ENV.get('DB_USER'),
        'PASSWORD': ENV.get('DB_PASSWORD'),
        'HOST': 'localhost',
        'PORT': '5432',
    },
}

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'es-pe'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = ''

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CKEDITOR_JQUERY_URL = '{}admin/js/vendor/jquery/jquery.js'.format(STATIC_URL)
CKEDITOR_UPLOAD_PATH = "uploads/"

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': [["Bold", "Italic", "Underline"],
            # ['TextColor', 'BGColor', '-', 'Rule'],
            ['NumberedList', 'BulletedList'],
            # ["Image", "Table", "Link", "Unlink", "Anchor", "SectionLink", "Subscript", "Superscript"], ['Undo', 'Redo'], ["Source"],
            ["Maximize"]],
        # 'height': 300,
        # 'width': 300,
        # "removePlugins": "Bold",
    },
}

GEOPOSITION_GOOGLE_MAPS_API_KEY = "AIzaSyAhzVqPFBfFHScF54ltTU66kIgXkKUXMNk"

ADMIN_REORDER = (
    # Keep original label and models

    # Reorder app models
    {'app': 'auth', 'label': 'Administración de Usuarios',
     'models': ('auth.user',
                )},
    {'app': 'web', 'label': 'General',
            'models': ('web.InfoSite',
                       'web.Banners',
                       )},
    {'app': 'web', 'label': 'Inicio',
            'models': ('web.Home',
                       'web.HomeBanner',
                       )},
    {'app': 'web', 'label': 'Somos',
            'models': ('web.Somos',
                       )},
    {'app': 'web', 'label': 'Testimonios',
            'models': ('web.Testimonio',
                       )},
    {'app': 'web', 'label': 'Servicios',
            'models': ('web.SeccionServicios',
                       'web.Servicio',
                       )},
    {'app': 'web', 'label': 'Clientes',
            'models': ('web.SeccionCliente',
                       'web.Cliente',
                       )},
    {'app': 'web', 'label': 'Contacto',
            'models': ('web.Contacto',
                       'web.SeccionContacto',
                       )},
    {'app': 'seo', 'label': 'SEO',
            'models': ('web.SEO',
                       )},
)
